sudo: enabled
dist: xenial
language: python
python:
  - "3.5"
# versions 3.6.0 and 3.6.1 have bugs that affect magneticod

before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install python3-dev"
  - "pip3 install mypy pylint"

install:
  - "pip3 install ./magneticod"
  - "pip3 install ./magneticow"

script:
  - "pylint ./magneticod/magneticod"
  - "pylint ./magneticow/magneticow"
  - "mypy ./magneticod/magneticod"
  - "mypy ./magneticow/magneticow"