version: "{branch}-{build}"

platform: x64

# Source Config
clone_folder: c:\gopath\src\magnetico
shallow_clone: true

# Build host
environment:
  GOPATH: c:\gopath
  GOVERSION: 1.15.6

install:
  # Install the specific Go version.
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - set Path=c:\go\bin;c:\gopath\bin
  - go version
  - go env
  - go get -u -v github.com/kevinburke/go-bindata/...
  - go get -u -v honnef.co/go/tools/cmd/staticcheck

before_build:
  - make staticcheck
  - make check-formatting

build_script:
  - make magneticod
  - make magneticow

test_script:
  - make test
