version: "2"

services:
  magneticod:
    image: boramalper/magneticod
    volumes:
      - ${MAGNETICOD_DATA}:/root/.local/share/magneticod
      - ${MAGNETICOD_CONFIG}:/root/.config/magneticod
    network_mode: "host"

  magneticow:
    image: boramalper/magneticow
    volumes:
      - ${MAGNETICOD_DATA}:/root/.local/share/magneticod
      - ${MAGNETICOW_CONFIG}:/root/.config/magneticow
    depends_on:
      # It doesn't necessarily "depend" on magneticod, but you would probably like to start them at the same time.
      - magneticod
    ports:
      - "8080:8080"
